baseURL = 'https://qgp9.github.io/hugo-smartlink-demo/'
relativeURLs = false
languageCode = 'en-us'
title = 'My New Hugo Site'


[module]
[[module.imports]]
path = 'github.com/McShelby/hugo-theme-relearn'
[[module.imports]]
path = 'github.com/qgp9/hugo-smartlink'
